default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['BOOKS_DATABASE_USER'] %>
  password: <%= ENV['BOOKS_DATABASE_PASSWORD'] %>
  host: localhost
 
development:
  <<: *default
  database: books_development